trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerRegSC: 'ACRAuth'
  imageRepository: 'devops-demo'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

steps:
- task: Docker@2
  displayName: 'Build and Push Docker Image'
  inputs:
    command: 'buildAndPush'
    containerRegistry: '$(dockerRegSC)'
    repository: '$(imageRepository)'
    dockerfile: '$(dockerfilePath)'
    tags: |
      $(tag)
      latest